### ISSUE TITLE
Need information on how the pairs work for watchdog

### ISSUE THREAD

**Issue by whardier** [duffolonious/mb7540-platform#2]
I am trying to set up a configuration where if the machine is in an expired state (machine is off or watchdog has timed out) then Port 1 and Port 2 are in bypass.  If the watchdog is being updated however the bypass should be shut off.

I've tried nearly every configuration permutation I can think of via the DIRECTIO due to the kernel module on several kernels causing panics.  Different issue :)

Any idea how to optimally configure this so that I can continue diagnosing this?

**Comment by whardier** [comment]
I don't really mind if the machine is hung up.  Ideally having a software bridge up and in forwarding mode before initializing the watchdog would be ideal.  When shutting down I'd like to gracefully enter bypass mode while the system does a normal reboot.. right before the bridge is taken down.

**Comment by duffolonious** [comment]
Hmmmm... I currently do the direct io calls because the kernel code is fairly unwieldy.

Are you only setting the "runtime" disabling of the pair?  Or "off-mode" bypass?

Does "wd_tst --dump" work for you?  And can you post the output?

Thanks.

**Comment by whardier** [comment]
I've tested both options.  I don't have access to the unit right now however.  Dump does show when I make changes that the changes have potentially been taken.

What would the ideal setup be for a proper configuration where the bypass is in place only if the watchdog is inactive or timed out?

BTW looking forward to solving this and helping contribute if I can.

**Comment by whardier** [comment]
Oooh.. it also appears as though we have the FW-7541 series.  There is perhaps a compatibility problem there.  I was handed this project with the 7540 code so I made an assumption about the compatibility.

**Comment by duffolonious** [comment]
I dunno off-hand.  Annoyingly, as I've seen on other hardware, it looks like it works - the settings appear to be set (reading from the i/o ports) but it just doesn't work.

**Comment by whardier** [comment]
That stinks.  Anything you need from me?  Access to the device, etc... ?

**Comment by duffolonious** [comment]
Ummmm... sure.  I'm also seeing if I can get more information about that unit from Lanner.

**Comment by whardier** [comment]
Awesome.  Just let me know and good luck.

**Comment by duffolonious** [comment]
I see if about getting the new 7541 stuff available in a new repository tonight.

**Comment by whardier** [comment]
Looking forward to testing it.. thank you for your efforts on this.

**Comment by duffolonious** [comment]
It's up (mb7541-platform), the main difference is what it usually is - GPIO change.
